// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDosb_Iyimf1lSukL_APGSe1YmmO-LkCro',
    appId: '1:322605028525:web:70e8de8f41b5fa17446224',
    messagingSenderId: '322605028525',
    projectId: 'biogas-3eac2',
    authDomain: 'biogas-3eac2.firebaseapp.com',
    databaseURL: 'https://biogas-3eac2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'biogas-3eac2.appspot.com',
    measurementId: 'G-TD7T6R8GWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5DMLEcLUn7AvfeATXUETgm3wZQJXPFVQ',
    appId: '1:322605028525:android:2fbcb292c9225807446224',
    messagingSenderId: '322605028525',
    projectId: 'biogas-3eac2',
    databaseURL: 'https://biogas-3eac2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'biogas-3eac2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC18oI84uQlOFbrtPhM8pwelaQooRoGOoI',
    appId: '1:322605028525:ios:dac5b7e83fc0c959446224',
    messagingSenderId: '322605028525',
    projectId: 'biogas-3eac2',
    databaseURL: 'https://biogas-3eac2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'biogas-3eac2.appspot.com',
    iosBundleId: 'com.example.biogasUmar',
  );
}
